### ISSUE TITLE
silent fail when run parallel and invalid image file

### ISSUE THREAD

**Issue by Ftelf** [Crunch-io/nightwatch-vrt#31]
When base image file is invalid ie. by bad checkout or corruption the test fails by:
`(node:109280) UnhandledPromiseRejectionWarning: Error: Invalid file signature
    at module.exports.Parser._parseSignature (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\parser.js:50:18)
    at module.exports.ChunkStream._processRead (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\chunkstream.js:174:13)
    at module.exports.ChunkStream._process (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\chunkstream.js:193:14)
    at module.exports.ChunkStream.write (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\chunkstream.js:61:8)
    at module.exports.ChunkStream.end (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\chunkstream.js:74:10)
    at exports.PNG.PNG.end (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\png.js:98:16)
    at exports.PNG.PNG.parse (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\pngjs\lib\png.js:88:8)
    at Jimp.parseBitmap (C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\jimp\index.js:297:17)
    at C:\git\vendavo-frontend\vendavo-price-optimization\node_modules\jimp\index.js:202:29
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)`
silently and does not report a fail:
`Process finished with exit code 0`

**Comment by Ftelf** [comment]
Fixed in PR https://github.com/Crunch-io/nightwatch-vrt/pull/32
